name: Releave next version

on:
  push:
    branches:
      - next

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Build
        run: npm run build
      - name: version
        run: npm run semantic-release
